# Generated by Django 6.0.4 on 2026-05-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AptCoord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complex_name", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=100)),
                ("road_address", models.CharField(blank=True, max_length=300)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["district"], name="apt_aptcoor_distric_3b659e_idx"
                    )
                ],
                "unique_together": {("complex_name", "district")},
            },
        ),
    ]
